# This file was generated by GoReleaser. DO NOT EDIT.
cask "converge" do
  name "converge"
  desc "Local-first experiment tracker for AI-assisted coding workflows"
  homepage "https://github.com/prit3010/converge"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "converge"

  on_macos do
    on_intel do
      url "https://github.com/prit3010/converge/releases/download/v#{version}/converge_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/prit3010/converge/"
      sha256 "f88a3e61f6817e22a2d035defc442a843226ea4df6aa65d22d7e655d93841b42"
    end
    on_arm do
      url "https://github.com/prit3010/converge/releases/download/v#{version}/converge_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/prit3010/converge/"
      sha256 "23ab71eb6ce2594ce9f53dbd15b215154e49349b33b6e158afb55c59f4ff0603"
    end
  end

  # No zap stanza required
end
