# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Converge < Formula
  desc "Local-first experiment tracker for AI-assisted coding workflows"
  homepage "https://github.com/prit3010/converge"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prit3010/converge/releases/download/v0.2.1/converge_0.2.1_darwin_amd64.tar.gz"
      sha256 "3c31d466bd8232e7873a4b5160a4ca6d872678d82040e95fc60c19a0c5aa1753"

      define_method(:install) do
        bin.install "converge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prit3010/converge/releases/download/v0.2.1/converge_0.2.1_darwin_arm64.tar.gz"
      sha256 "9f787e2692412f9c91a99e80ced777c49386e8da8015284b49d106d15e235be4"

      define_method(:install) do
        bin.install "converge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prit3010/converge/releases/download/v0.2.1/converge_0.2.1_linux_amd64.tar.gz"
      sha256 "e620ab41714814004d5200b5d43de49e5acfea671a339f5d53b2e3ebe6987024"
      define_method(:install) do
        bin.install "converge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prit3010/converge/releases/download/v0.2.1/converge_0.2.1_linux_arm64.tar.gz"
      sha256 "d74c224cc584c23c7221530cff3627c8f8e0533185ecd837d149c5459fc3f79c"
      define_method(:install) do
        bin.install "converge"
      end
    end
  end

  test do
    system "#{bin}/converge", "version"
  end
end
